name: Foundry Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Run Forge coverage
        run: |
          forge coverage --report lcov
        id: coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          verbose: true

      - name: Check code coverage
        run: |
          COVERAGE=$(forge coverage --report summary | tail -1 | awk '{print $NF}' | sed 's/%//')
          if (( $(echo "$COVERAGE < 95" | bc -l) )); then
            echo "Code coverage is below 95%. Current coverage: $COVERAGE%"
            exit 1
          fi
        id: coverage-check

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          target: "."
          slither-args: "--exclude naming-convention,external-function,low-level-calls"

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: lcov.info
